import pandas as pd
import mne
from mne_nirs.experimental_design import longest_inter_annotation_interval
from nilearn.glm.first_level import make_first_level_design_matrix
# from mne_nirs.experimental_design import make_first_level_design_matrix
from mne_nirs.statistics import run_glm
from mne_nirs.channels import get_short_channels
from pandas import DataFrame

from joblib import Parallel, delayed

from rpy2.robjects import r, globalenv
from rpy2.robjects.packages import importr
from rpy2.robjects.conversion import localconverter
from rpy2.robjects import pandas2ri
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.formula.api as smf
from mne_nirs.statistics import statsmodels_to_results
from mne_nirs.visualisation import plot_glm_group_topo, plot_glm_surface_projection

import os
from dotenv import load_dotenv
from pathlib import Path

from sklearn.decomposition import PCA
from mne.preprocessing import ICA

load_dotenv()
save_path = Path(os.getenv(rf"data_save_path"))
Phase_1_assumptions_plot_save_path = Path(os.getenv(rf"Phase_1_assumptions_plot_save_path"))
Phase_1_ANOVA_save_path = Path(os.getenv(rf"Phase_1_ANOVA_save_path"))
Phase_2_assumptions_plot_save_path = Path(os.getenv(rf"Phase_2_assumptions_plot_save_path"))
Phase_2_ANOVA_save_path = Path(os.getenv(rf"Phase_2_ANOVA_save_path"))

from mne.io.pick import _picks_to_idx
from nilearn.glm.first_level import run_glm as nilearn_glm
from mne_nirs.statistics import RegressionResults

def run_glm(method, raw, design_matrix, noise_model="ar1", bins=0, n_jobs=1, verbose=0):
    """
    GLM fit for an MNE structure containing fNIRS data.

    This is a wrapper function for nilearn.stats.first_level_model.run_glm.

    Parameters
    ----------
    raw : instance of Raw
        The haemoglobin data.
    design_matrix : as specified in Nilearn
        The design matrix as generated by
        `mne_nirs.make_first_level_design_matrix`.
        See example ``9.5.5. Examples of design matrices`` at
        https://nilearn.github.io/auto_examples/index.html
        for details on how to specify design matrices.
    noise_model : {'ar1', 'ols', 'arN', 'auto'}, optional
        The temporal variance model. Defaults to first order
        auto regressive model 'ar1'.
        The AR model can be set to any integer value by modifying the value
        of N. E.g. use `ar5` for a fifth order model.
        If the string `auto` is provided a model with order 4 times the sample
        rate will be used.
    bins : int, optional
        Maximum number of discrete bins for the AR coef histogram/clustering.
        By default the value is 0, which will set the number of bins to the
        number of channels, effectively estimating the AR model for each
        channel.
    n_jobs : int, optional
        The number of CPUs to use to do the computation. -1 means
        'all CPUs'.
    verbose : int, optional
        The verbosity level. Default is 0.

    Returns
    -------
    glm_estimates : RegressionResults
        RegressionResults class which stores the GLM results.
    """
    sum_method = lambda data: np.sum(data, axis=0)
    if method == "PCA_HbT":
        raw_copy = raw.copy()
        raw_copy_hbo = raw_copy.copy().pick("hbo")
        raw_copy_hbr = raw_copy.copy().pick("hbr")
        raw_hbo = raw_copy_hbo.get_data()
        raw_hbr = raw_copy_hbr.get_data()
        Sigma_hbo = np.cov(raw_hbo)
        Sigma_hbr = np.cov(raw_hbr)
        eigenvalues_hbo, eigenvectors_hbo = np.linalg.eigh(Sigma_hbo)
        eigenvalues_hbr, eigenvectors_hbr = np.linalg.eigh(Sigma_hbr)
        idx_hbo = np.argsort(eigenvalues_hbo)[::-1]
        eigenvalues_hbo = eigenvalues_hbo[idx_hbo]
        eigenvectors_hbo = eigenvectors_hbo[:, idx_hbo]
        idx_hbr = np.argsort(eigenvalues_hbr)[::-1]
        eigenvalues_hbr = eigenvalues_hbr[idx_hbr]
        eigenvectors_hbr = eigenvectors_hbr[:, idx_hbr]
        pca_hbo = eigenvectors_hbo[:, 0] @ raw_hbo
        pca_hbr = eigenvectors_hbr[:, 0] @ raw_hbr
        for ch in raw_copy.info["chs"]:
                if ch["kind"] == mne.io.constants.FIFF.FIFFV_FNIRS_CH:
                    ch["coil_type"] = mne.io.constants.FIFF.FIFFV_COIL_FNIRS_HBO
        groups = {"PC_channel": [i for i, ch in enumerate(raw_copy.ch_names)]}
        pca_method = lambda data: pca_hbo + pca_hbr
        raw_pca = mne.channels.combine_channels(
            raw_copy, 
            groups=groups, 
            method=pca_method)
        glm_raw = raw_pca.copy()
        picks = _picks_to_idx(glm_raw.info, "fnirs", exclude=[], allow_empty=True)
        ch_names = list(groups.keys())
    
    elif method == "PCA":
        raw_copy = raw.copy()
        raw_copy_hbo = raw_copy.copy().pick("hbo")
        raw_copy_hbr = raw_copy.copy().pick("hbr")
        raw_hbo = raw_copy_hbo.get_data()
        raw_hbr = raw_copy_hbr.get_data()
        pca_hbo =  PCA().fit_transform(raw_hbo.T)
        pca_hbr =  PCA().fit_transform(raw_hbr.T)
        pca_hbo_first_PCA = pca_hbo[:, 0:1].T
        pca_hbr_first_PCA = pca_hbr[:, 0:1].T
        
        pca_channel_names = [f"PC1_hbo", f"PC1_hbr"]
        groups = {ch_name: [i for i, ch in enumerate(raw_copy.ch_names) if ch.split(" ")[1] in ch_name.split("_")[1]] for ch_name in pca_channel_names}
        for ch in raw_copy.info["chs"]:
                if ch["kind"] == mne.io.constants.FIFF.FIFFV_FNIRS_CH:
                    ch["coil_type"] = mne.io.constants.FIFF.FIFFV_COIL_FNIRS_HBO
        pca_data = np.vstack([pca_hbo_first_PCA, pca_hbr_first_PCA])
        info = mne.create_info(
        ch_names=["PC1_hbo", "PC1_hbr"],
        sfreq=raw_copy.info["sfreq"],
        ch_types=["hbo", "hbr"]
        )
        glm_raw = mne.io.RawArray(pca_data, info)
        picks = _picks_to_idx(glm_raw.info, "fnirs", exclude=[], allow_empty=True)
        ch_names = list(groups.keys())
    
    elif method == "ICA":
        raw_copy = raw.copy()
        raw_copy_hbo = raw_copy.copy().pick("hbo")
        raw_copy_hbr = raw_copy.copy().pick("hbr")
        ica_hbo = ICA(random_state=97)
        ica_hbo.fit(raw_copy_hbo)
        ica_hbr = ICA(random_state=97)
        ica_hbr.fit(raw_copy_hbr)
        raw_hbo_clean = ica_hbo.apply(raw_copy_hbo)
        raw_hbr_clean = ica_hbr.apply(raw_copy_hbr)
        glm_raw = raw_hbo_clean.add_channels([raw_hbr_clean])
        picks = _picks_to_idx(glm_raw.info, "fnirs", exclude=[], allow_empty=True)
        ch_names = list(glm_raw.ch_names)
        
    elif method == "HbT":
        raw_tmp = raw.copy()
        for ch in raw_tmp.info["chs"]:
            if ch["kind"] == mne.io.constants.FIFF.FIFFV_FNIRS_CH:
                ch["coil_type"] = mne.io.constants.FIFF.FIFFV_COIL_FNIRS_HBO # We set the channel types to HbO to allow combination
        ch_names = list(set([ch_name.strip("hbo").strip("hbr") + "HbT" for ch_name in raw_tmp.ch_names]))
        groups = {ch_name: [i for i, ch in enumerate(raw.ch_names) if ch.strip(" hbo").strip(" hbr") in ch_name.strip(" HbT")] for ch_name in ch_names}
        raw_HbT = mne.channels.combine_channels(
        raw_tmp, 
        groups=groups, 
        method=sum_method)
        glm_raw = raw_HbT.copy()
        picks = _picks_to_idx(glm_raw.info, "fnirs", exclude=[], allow_empty=True)
    elif method == "Standard":
        glm_raw = raw.copy()
        picks = _picks_to_idx(glm_raw.info, "fnirs", exclude=[], allow_empty=True)
        ch_names = raw.ch_names

    if noise_model == "auto":
        noise_model = f"ar{int(np.round(glm_raw.info['sfreq'])) * 4}"

    if bins == 0:
        bins = len(glm_raw.ch_names)

    results = dict()
    for pick in picks:
        labels, glm_estimates = nilearn_glm(
            glm_raw.get_data(pick).T,
            design_matrix.values,
            noise_model=noise_model,
            bins=bins,
            n_jobs=n_jobs,
            verbose=verbose,
        )
        results[ch_names[pick]] = glm_estimates[labels[0]]

    return RegressionResults(glm_raw.info, results, design_matrix)
    
def run_glm_analysis(subjects, class_instance, drift_model="cosine", hrf_model="glover", number_of_subjects=[]):
    
    print("Running GLM analysis")
    def glm_subject(subject, idx, data_types, drift_model, hrf_model):
        print(f"Constructing design matrix and running GLM on subject {idx+1}/{len(subjects)}")
        haemo = subject.raw_haemo.copy()
        relevant_channels = haemo.ch_names #[ch for ch in haemo.ch_names if ("S1" in ch) or ("S2" in ch) or ("S3" in ch) or ("S4" in ch)] #
        haemo = haemo.pick(picks=relevant_channels)
        
        redundant_annotations = [x for x in np.unique(haemo.annotations.description) if x not in set(data_types)]
        if len(redundant_annotations) != 0:
            for annotation in redundant_annotations:
                haemo.annotations.delete(haemo.annotations.description == annotation)
        renames_isis = {cond: cond.split("/")[0] if "/" in cond else cond for cond in haemo.annotations.description}
        renames = {cond: cond.split("/")[1] if "/" in cond else cond for cond in haemo.annotations.description}
        haemo_isis = haemo.copy()
        haemo_isis.annotations.rename(renames_isis)
        haemo.annotations.rename(renames_isis)
        short_channel_haemo = get_short_channels(subject.raw_haemo_unfiltered)
        # haemo.resample(2.5, npad="auto")
        # short_channel_haemo.resample(2.5, npad="auto")
        isis, names = longest_inter_annotation_interval(haemo_isis)
        
        conditions = haemo.annotations.description
        
        high_pass_value = 1/(max(isis)*2)
        onsets = haemo.annotations.onset - haemo.first_time
        duration = haemo.annotations.duration
        
        frame_times = haemo.times
        events = DataFrame({'trial_type': conditions,
                    'onset': onsets,
                    'duration': duration})
        drift_model=drift_model
        hrf_model = hrf_model
        min_onset = 0 # Normally used for fMRI in case events are coded relative to a trigger that happens before scanning. Not relevant here.
        high_pass = high_pass_value #high_pass_value
        add_regs = short_channel_haemo.get_data().T * 10**6 # Scale to uM
        oversampling = 1 # Default value.
        drift_order = 1 # When we use the cosine drift model this parameter doesn't really matter, as the drift order is then actually determined by the high_pass argument
        add_reg_names = short_channel_haemo.ch_names
        fir_delays = range(21) # Default when we don't use a FIR model
        from nilearn.glm.first_level.hemodynamic_models import _calculate_tr
        from nilearn.glm.first_level.hemodynamic_models import _gamma_difference_hrf
        from functools import partial
        t_r = _calculate_tr(frame_times)    
        hrf_model_ = partial(
        _gamma_difference_hrf,
        time_length=32.0,
        onset=min_onset,
        delay=7,
        undershoot=12.0,
        dispersion=0.9,
        u_dispersion=0.9,
        ratio=0.48,
        )
        hrf_model_.__name__ = '_gamma_custom_delay_hrf'
        
        try:
            design_matrix = make_first_level_design_matrix(frame_times,
                                            events,
                                            drift_model=drift_model,
                                            drift_order=drift_order,
                                            hrf_model=hrf_model_,
                                            min_onset=min_onset,
                                            high_pass=high_pass,
                                            add_regs=add_regs,
                                            oversampling=oversampling,
                                            add_reg_names=add_reg_names,) 
            glm_estimates = run_glm("HbT", haemo, design_matrix, n_jobs=1)

        except Exception as e:
            print(f"Error type: {type(e).__name__}")
            print(f"Error message: {str(e)}")
            import traceback
            traceback.print_exc()
            raise
        
        # Create a single ROI that includes all channels for example
        # rois = dict(AllChannels=range(len(haemo.ch_names)))
        rois = dict(AllChannels=[i for i, ch in enumerate(haemo.ch_names) if ("S2" in ch) or ("S10" in ch)])
        # rois = dict(
        # Left=[i for i, ch in enumerate(haemo.ch_names) if "S2" in ch],
        # Right=[i for i, ch in enumerate(haemo.ch_names) if "S12" in ch]
        # )

        # Calculate ROI for all conditions
        conditions = design_matrix.columns
        
        # Compute output metrics by ROI
        # df_ind = glm_estimates.to_dataframe_region_of_interest(rois, conditions)
        cha = glm_estimates.to_dataframe()
        
        hrf_model_suffix = f"_{hrf_model_.__name__}"
        cha["Condition"] = cha["Condition"].str.replace(hrf_model_suffix, "", regex=False) # Remove the HRF model name from the name of the conditions
        #df_ind["ID"] = 
        cha["ID"] = subject.name + "_" + "HC" if idx < number_of_subjects[0] else subject.name + "_" + "Patient"
        cha["Group"] = "HC" if idx < number_of_subjects[0] else "Patient"
        
        # Convert to uM for nicer plotting below.
        # df_ind["theta"] = [t * 1.0e6 for t in df_ind["theta"]]
        cha["theta"] = [t * 1.0e6 for t in cha["theta"]]

        
        return haemo, design_matrix, cha
    
    results = Parallel(n_jobs=1)(
    delayed(glm_subject)(subject, idx, class_instance.data_types, drift_model,hrf_model)
    for idx, subject in enumerate(subjects)
    )

    haemos, design_matrices, cha_dfs = zip(*results)

    # betas_roi_df = pd.concat(subject_dfs, ignore_index=True)

    if hrf_model == "fir":
        plot_group_fir_model(betas_roi_df, "Tongue", design_matrices[0], raw_haemo=subjects[0].raw_haemo)
    
    else:
        data_types = list(np.unique(haemos[0].annotations.description))

        betas_cha_df = pd.concat(cha_dfs, ignore_index=True)
        betas_cha_df = betas_cha_df.query("Condition in @data_types")
        # Cut down the dataframe just to the conditions we are interested in
        data_types = [data_types[0], data_types[-1]]
        ch_summary = betas_cha_df.query("Condition in @data_types")

        # Save the dataframe to verify it's identical
        # ch_summary.to_csv(rf"C:\Users\NKUE0003\OneDrive - Region Hovedstaden\Bachelor\Results\debug_ch_summary.csv", index=False)
        with localconverter(pandas2ri.converter):
            globalenv["rdf"] = ch_summary
        globalenv["Phase_1_assumptions_plot_save_path"] = str(Phase_1_assumptions_plot_save_path).replace("\\", "/")
        globalenv["Phase_2_assumptions_plot_save_path"] = str(Phase_2_assumptions_plot_save_path).replace("\\", "/")

        lme4 = importr("lme4")
        
        r('''
        library(lme4)
        library(lmerTest)
        library(performance)
        library(see)
        library(ggplot2)
        library(patchwork)
        library(effectsize)
        library(simr)
        
        # Create all three models
        # modelConch_plot <- lmer(theta ~ Condition + ch_name + Condition:ch_name + (1 | ID), 
        #                         data=rdf, REML=TRUE)
        # modelchannel_plot <- lmer(theta ~ Condition + ch_name + (1 | ID), 
        #                         data=rdf, REML=TRUE)
        # modelCondition_plot <- lmer(theta ~ Condition + (1 | ID), 
        #                             data=rdf, REML=TRUE)

        # # Get diagnostic plots for all models
        # diag_conch <- plot(check_model(modelConch_plot, panel = FALSE))
        # diag_channel <- plot(check_model(modelchannel_plot, panel = FALSE))
        # diag_condition <- plot(check_model(modelCondition_plot, panel = FALSE))

        # # Define plot names
        # plot_names <- c(
        #     "posterior_predictive_check",
        #     "linearity",
        #     "homogeneity_of_variance",
        #     "influential_outliers",
        #     "multicollinearity",
        #     "normal_residuals"
        # )

        # # Combine and save each diagnostic type across all three models
        # for(i in seq_along(plot_names)) {
        #     filename <- file.path(Phase_1_assumptions_plot_save_path, 
        #                         paste0("combined_", plot_names[i], ".pdf"))
            
        #     tryCatch({
        #         # Combine the three plots horizontally with titles
        #         combined_plot <- (diag_conch[[i]] + ggtitle("Model: Condition × Channel")) | 
        #                         (diag_channel[[i]] + ggtitle("Model: Condition + Channel")) | 
        #                         (diag_condition[[i]] + ggtitle("Model: Condition Only"))
                
        #         # Save combined plot
        #         ggsave(filename, plot = combined_plot, width = 18, height = 6, device = "pdf")
        #         message(paste("✓ Created:", filename))
        #     }, error = function(e) {
        #         message(paste("✗ Could not create:", plot_names[i], "-", e$message))
        #     })
        # }

        # message("All combined diagnostic plots completed!")
                
        modelConch <- lmer(theta ~ Condition + ch_name + Condition:ch_name + (1 | ID), data=rdf, REML=FALSE)
        nullModelConch <- lmer(theta ~ Condition + ch_name + (1 | ID), data=rdf, REML=FALSE)
        anova_result_Condch <- anova(modelConch, nullModelConch)
        anova_Condch_df <- as.data.frame(anova_result_Condch)
        print(anova_result_Condch)
        # # print(isSingular(modelConch, tol = 1e-4))
        # # print(summary(modelConch)$varcor)
        # X <- model.matrix(~ Condition * ch_name, data = rdf)
        # # print(qr(X)$rank)
        # # print(ncol(X))
        
        # #Extract coefficents as dataframe:
        # coef_summary_modelConch <- as.data.frame(summary(modelConch)$coefficients)
        # coef_summary_modelConch$Parameter <- rownames(coef_summary_modelConch)
        # colnames(coef_summary_modelConch) <- c("Estimate", "Std_Error", "df", "t_value", "p_value", "Parameter")

        # #Extract coefficents for plotting:
        # coef_summary_nullModelConch <- as.data.frame(summary(nullModelConch)$coefficients)
        # coef_summary_nullModelConch$Parameter <- rownames(coef_summary_nullModelConch)
        # colnames(coef_summary_nullModelConch) <- c("Estimate", "Std_Error", "df", "t_value", "p_value", "Parameter")
        
        # ################################################################################################################
        
        modelchannel <- lmer(theta ~ Condition + ch_name + (1 | ID), data=rdf, REML=FALSE)
        nullModelchannel <- lmer(theta ~ Condition + (1 | ID), data=rdf, REML=FALSE)
        anova_result_channel <- anova(modelchannel, nullModelchannel)
        anova_channel_df <- as.data.frame(anova_result_channel)
        print(anova_result_channel)
        
        # #Extract coefficents as dataframe:
        # coef_summary_modelchannel <- as.data.frame(summary(modelchannel)$coefficients)
        # coef_summary_modelchannel$Parameter <- rownames(coef_summary_modelchannel)
        # colnames(coef_summary_modelchannel) <- c("Estimate", "Std_Error", "df", "t_value", "p_value", "Parameter")
        
        # #Extract coefficents for plotting:
        # coef_summary_nullModelchannel <- as.data.frame(summary(nullModelchannel)$coefficients)
        # coef_summary_nullModelchannel$Parameter <- rownames(coef_summary_nullModelchannel)
        # colnames(coef_summary_nullModelchannel) <- c("Estimate", "Std_Error", "df", "t_value", "p_value", "Parameter")

        # ################################################################################################################
        
        modelCondition <- lmer(theta ~ Condition + (1 | ID), data=rdf, REML=FALSE)
        nullModelCondition <- lmer(theta ~ (1 | ID), data=rdf, REML=FALSE)
        anova_result_condition <- anova(modelCondition, nullModelCondition)
        anova_condition_df <- as.data.frame(anova_result_condition)
        print(anova_result_condition)
        
        # Fit the model
        modelCondition_ML <- lmer(theta ~ Condition + (1 | ID), data=rdf, REML=FALSE)
        print(summary(modelCondition_ML))
        model_sim <- modelCondition_ML
        power_original <- powerSim(model_sim, nsim = 200, test = fixed("Condition"))
        print(summary(power_original))

        #Extract coefficents as dataframe:
        coef_summary_modelCondition <- as.data.frame(summary(modelCondition)$coefficients)
        coef_summary_modelCondition$Parameter <- rownames(coef_summary_modelCondition)
        colnames(coef_summary_modelCondition) <- c("Estimate", "Std_Error", "df", "t_value", "p_value", "Parameter")
        
        #Extract coefficents for plotting:
        coef_summary_nullModelCondition<- as.data.frame(summary(modelCondition)$coefficients)
        coef_summary_nullModelCondition$Parameter <- rownames(coef_summary_nullModelCondition)
        colnames(coef_summary_nullModelCondition) <- c("Estimate", "Std_Error", "df", "t_value", "p_value", "Parameter")

        ################################################################################################################

        # Create the model
        # modelGroup_plot <- lmer(theta ~ Condition:Group:ch_name + Condition:ch_name + Condition:Group + Group:ch_name + Condition + ch_name + Group + (1 | ID), data=rdf, REML=TRUE)
        modelGroup <-  lmer(theta ~ Condition:Group:ch_name + Condition:ch_name + Condition:Group + Group:ch_name + Condition + ch_name + Group + (1 | ID), data=rdf, REML=FALSE)
        print(anova(modelGroup))

        # # Get all diagnostic plots as a list of ggplot objects
        # diagnostic_plots <- plot(check_model(modelGroup_plot, panel = FALSE))

        # # Define plot names for each position
        # plot_names <- c(
        #     "posterior_predictive_check",  # [[1]]
        #     "linearity",                   # [[2]]
        #     "homogeneity_of_variance",     # [[3]]
        #     "influential_outliers",        # [[4]]
        #     "multicollinearity",           # [[5]]
        #     "normal_residuals"             # [[6]]
        # )

        # # Save each plot individually
        # for(i in seq_along(diagnostic_plots)) {
        #     filename <- file.path(Phase_2_assumptions_plot_save_path, paste0("modelGroup_", plot_names[i], ".pdf"))
            
        #     tryCatch({
        #         ggsave(filename, plot = diagnostic_plots[[i]], width = 8, height = 6, device = "pdf")
        #         message(paste("✓ Created:", filename))
        #     }, error = function(e) {
        #         message(paste("✗ Could not create:", plot_names[i], "-", e$message))
        #     })
        # }

        # # Also save the complete panel
        # pdf(file.path(Phase_2_assumptions_plot_save_path, "modelGroup_all_diagnostics.pdf"), width = 12, height = 10)
        # diagnostic_plots <- plot(check_model(modelGroup_plot))
        # dev.off()

        # message("All diagnostic plots completed!")
        
        # modelGroup <- lmer(theta ~ Condition:Group:ch_name + Condition:ch_name + Condition:Group + Group:ch_name + Condition + ch_name + Group + (1 | ID), data=rdf, REML=FALSE)
        # nullModelGroup <- lmer(theta ~ Condition:ch_name + Condition:Group + Group:ch_name + Condition + ch_name + Group + (1 | ID), data=rdf, REML=FALSE)
        # anova_result_group <- anova(modelGroup, nullModelGroup)
        # anova_group_df <- as.data.frame(anova_result_group)
        # print(anova_result_group)
        
        # #Extract coefficents as dataframe:
        # coef_summary_modelGroup <- as.data.frame(summary(modelGroup)$coefficients)
        # coef_summary_modelGroup$Parameter <- rownames(coef_summary_modelGroup)
        # colnames(coef_summary_modelGroup) <- c("Estimate", "Std_Error", "df", "t_value", "p_value", "Parameter")
        
        # #Extract coefficents for plotting:
        # coef_summary_nullModelGroup<- as.data.frame(summary(modelCondition)$coefficients)
        # coef_summary_nullModelGroup$Parameter <- rownames(coef_summary_nullModelGroup)
        # colnames(coef_summary_nullModelGroup) <- c("Estimate", "Std_Error", "df", "t_value", "p_value", "Parameter")
        ''')
        
        with localconverter(pandas2ri.converter):
            # anova_Condch_df = globalenv["anova_Condch_df"]
            # coef_summary_modelConch = globalenv["coef_summary_modelConch"]
            # coef_summary_nullModelConch = globalenv["coef_summary_nullModelConch"]
            
            
            # anova_channel_df = globalenv["anova_channel_df"]
            # coef_summary_modelchannel = globalenv["coef_summary_modelchannel"]
            # coef_summary_nullModelchannel = globalenv["coef_summary_nullModelchannel"]
            
            anova_condition_df = globalenv["anova_condition_df"]
            coef_summary_modelCondition = globalenv["coef_summary_modelCondition"]
            coef_summary_nullModelCondition = globalenv["coef_summary_nullModelCondition"]

            # anova_Group_df = globalenv["anova_group_df"]
            # coef_summary_modelGroup = globalenv["coef_summary_modelGroup"]
            # coef_summary_nullModelGroup = globalenv["coef_summary_nullModelGroup"]
            # anova_Group_df = globalenv["anova_group_df"]
            # coef_summary_modelGroup = globalenv["coef_summary_modelGroup"]
            # coef_summary_nullModelGroup = globalenv["coef_summary_nullModelGroup"]
            
            # results = globalenv["results_for_plotting"]
        # anova_Condch_df.to_csv(os.path.join(save_path, f"anova_Condch_df.csv"))
        # anova_channel_df.to_csv(os.path.join(save_path, f"anova_channel_df.csv"))
        anova_condition_df.to_csv(os.path.join(save_path, f"anova_condition_df.csv"))
        # anova_Group_df.to_csv(os.path.join(save_path, f"anova_group_df.csv"))
        # anova_Group_df.to_csv(os.path.join(save_path, f"anova_group_df.csv"))

import sys
parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(parent_dir)
from collections import defaultdict
from preprocessing_toolbox.load_data_function import data_loaders

dataSetList = list(data_loaders.keys())
dataLoaders = [dataSetList[12]] #, dataSetList[17]]
datasets = defaultdict(defaultdict)

for data_loader in dataLoaders:
    settings = {
        "data_set": data_loader,  # Default to first dataset
        "epoch_type": "TongueMI",
        "individual": "All Individuals",
        "short_channel_correction": True,
        "negative_correlation_enhancement": False,
        "haemo_type": "hbo",
        "baseline_correction": "Previous rest period",
        "tmin": 0,
        "stimulus_duration": 5,
        "scalp_coupling_threshold": 0.8,
        "reject_criteria": dict(hbo=80e-6),
        "unwanted": ["15.0"],
        "filter_lower_value": 0.01,
        "filter_upper_value": 0.5,
        "h_trans_bandwidth": 0.2,           
        "l_trans_bandwidth": 0.01,
        "snr_rejection": "SNR",  # Default to None, can be set to "SNR" or "CV"
        "snr_threshold": 8,  # Default threshold for SNR
        "Apply_TDDR": True,
        "interpolate_bad_channels": True,
    }
    current_loader = data_loaders[data_loader](
                    data_name = data_loader,
                    file_path = data_loader,
                    short_channel_correction=settings["short_channel_correction"],
                    negative_correlation_enhancement=settings["negative_correlation_enhancement"],
                    interpolate_bad_channels=settings["interpolate_bad_channels"],
                    baseline_correction=settings["baseline_correction"],
                    tmin=settings["tmin"],
                    filter_lower_value=settings["filter_lower_value"],
                    filter_upper_value=settings["filter_upper_value"],
                    l_trans_bandwidth=settings["l_trans_bandwidth"],
                    h_trans_bandwidth=settings["h_trans_bandwidth"],
                    scalp_coupling_threshold=settings["scalp_coupling_threshold"],
                    reject_criteria=settings["reject_criteria"],
                    snr_rejection=settings["snr_rejection"],
                    snr_threshold=settings["snr_threshold"],
                    apply_tddr=settings["Apply_TDDR"]
                )
    data = current_loader.load_data()
    variables = ("all_epochs", "data_name", "all_data", "freq", "data_types", "all_individuals")
    datasets[data_loader] = {key: value for key, value in zip(variables, data)}

all_participants = datasets[dataLoaders[0]]["all_individuals"] #+ datasets[dataLoaders[1]]["all_individuals"]
number_of_subjects = [len(datasets[dataLoaders[0]]["all_individuals"])] #, len((datasets[dataLoaders[1]]["all_individuals"]))]
run_glm_analysis(all_participants, current_loader, "cosine", "glover", number_of_subjects)